package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.accessingdatamysql.user.Player;
import com.example.accessingdatamysql.user.PlayerRepository;
import com.example.accessingdatamysql.user.PlayerState;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/api") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private PlayerRepository playerRepository;

  @PostMapping(path = "/players") // Map ONLY POST Requests
  public @ResponseBody String addNewPlayer(@RequestParam String name, @RequestParam String surname,
      @RequestParam String email, @RequestParam String password, @RequestParam String nickname) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Player n = new Player();
    n.setName(name);
    n.setSurname(surname);
    n.setEmail(email);
    n.setPassword(password);
    n.setNickname(nickname);
    n.setPlayerState(PlayerState.NO_PLAY);
    playerRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/players")
  public @ResponseBody Iterable<Player> getAllPlayers() {
    // This returns a JSON or XML with the users
    return playerRepository.findAll();
  }
}